In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle 
from sklearn.manifold import TSNE
import seaborn as sns 
sns.set_theme()

In [95]:
pickle_file = "/home/umaima.rahman/research/sem6/TPT/tpt_pickle/TPT_covid.pkl"

In [96]:
# Load the pickle file
with open(pickle_file, 'rb') as f:
    loaded_dict = pickle.load(f)

In [97]:
# Display the loaded dictionary
print("Loaded Dictionary:")
# print(loaded_dict['Z'])
print(loaded_dict['Yhat'])
print(loaded_dict['Ytrue'])
# print(loaded_dict['fpr'])
# print(loaded_dict['tpr'])
# print(loaded_dict['roc_auc'])
print(loaded_dict['f1'])

Loaded Dictionary:
[0. 0. 0. ... 0. 0. 0.]
[1. 1. 1. ... 1. 1. 1.]
0.0


In [34]:
Z = loaded_dict['Z']
Yhat = loaded_dict['Yhat']
Ytrue = loaded_dict['Ytrue']



In [35]:
# Combine the data into a single array for t-SNE visualization
data = list(Z,Yhat)

TypeError: list expected at most 1 argument, got 2

In [ ]:
tsne = TSNE(n_components=2, random_state=42)

In [ ]:
tsne_data = tsne.fit_transform(data)

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(Ytrue, Yhat)

array([[15,  0],
       [14,  0]])